language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
	
env:
- DJANGO=1.3
- DJANGO=1.4

install: 
- pip install -q Django = $DJANGO
- pip install -r requiments/dev.txt 

script: python manage.py test
